### ISSUE TITLE
change the HSL of each node

### ISSUE THREAD

**Issue by hooman-sarv** [edi-riga/tsch-sim#1]
Hi. can I change HSL of each node?
another question. I have a simple tree of my network. how can I give it as an input to the simulator?

**Comment by atiselsts** [comment]
Hello,

See parameter `MAC_HOPPING_SEQUENCE` in https://github.com/edi-riga/tsch-sim/wiki/Configuration#network-stack-parameters.
You can set parameters globally (in the top scope of the JSON file) or for each node type.

This is an example config file that defines three different hopping sequences for three different nodes. `node1` uses the global hopping sequence, `node2` and `node3` use their own values.

```
{
    "MAC_HOPPING_SEQUENCE": [15, 20, 25, 26],
    "NODE_TYPES": [
        {
            "NAME": "node1",
            "COUNT": 1,
            "START_ID" : 1,
            "CONNECTIONS" : [{"TO_NODE_TYPE" : "node2"}, {"TO_NODE_TYPE" : "node3"}]
        },
        {
            "NAME": "node2",
            "COUNT": 1,
            "START_ID" : 2,
            "MAC_HOPPING_SEQUENCE": [15, 20],
            "CONNECTIONS" : [{"TO_NODE_TYPE" : "node1"}]
        },
        {
            "NAME": "node3",
            "COUNT": 1,
            "START_ID" : 3,
            "MAC_HOPPING_SEQUENCE": [25, 26],
            "CONNECTIONS" : [{"TO_NODE_TYPE" : "node1"}]
        }
    ]
}

```

Please look at examples, maybe they can help with your second question. If not, clarify it here.
