### ISSUE TITLE
Define some nodes relays which only transmit the received packet to upper level nodes until the packet reaches the sink node

### ISSUE THREAD

**Issue by AidaVatankhah2022** [edi-riga/tsch-sim#36]
I have set the config.json, schedule.json and routes.json files as attached. 
[routs.json](https://github.com/edi-riga/tsch-sim/files/14352611/routs.json)
[config.json](https://github.com/edi-riga/tsch-sim/files/14352675/config.json)
[schedule.json](https://github.com/edi-riga/tsch-sim/files/14352690/schedule.json)

I used the below tree topology:
         A
      /             \\
B    C
    |
   D
A(ID=1), B(ID=2), D(ID=3), C(ID=4)
I set APP_PACKET_PERIOD_SEC for node D to 2 and for the rest of the nodes I set this value to 0. In this case, node D is the only node that can generate packets. The generated packet from node D is sent to nod
e B, and node B should be able to transmit (relay) the packet to node A. But this is not happening. I tried to implement this example, however, all of the packets generated by node D are lost and none is received. 
I tried several examples. Packets are only received in one scenario, only when the packet generator node is in one hope by the sink node (node A here). For example, if you set node B or node C as packet generator nodes, all packets will be received.
Please advise on this matter as it is very necessary for me to have some nodes as packet generators and some nodes only for relaying packets toward the sink node without generating any packets themselves.

**Comment by AidaVatankhah2022** [comment]
I believe we should check the "app_num_tx" and "app_num_endpoint_rx" filed for node B to confirm that this node is not transmitting the received packets.

**Comment by atiselsts** [comment]
Hi,

> I set APP_PACKET_PERIOD_SEC for node D to 2 and for the rest of the nodes I set this value to 0.

This is incorrect. The default value of `APP_PACKET_PERIOD_SEC` is 60 (seconds), not zero, I think you mentioned this in email yourself. As a result, the nodes A, B, and C generate packets once 60 seconds.

> node B should be able to transmit (relay) the packet to node A. But this is not happening

Your configuration works for me. I have put them in git [here](https://github.com/edi-riga/tsch-sim/tree/exp/aida-config), both the original version (only reformatted the JSON for readability, nothing else changed) and a version where just node D generates any packets.

I noticed that your have `"ROUTING_ALGORITHM": "ManualRouting"` and `"SCHEDULING_ALGORITHM": "NewScheduler"` set in the configuration, these are not part of the TSCH-Sim distribution, and will be ignored if you run the GitHub's version of the code. If you have made some changes in the TSCH-Sim code itself, that may be the cause why the setup has stopped working for you.
